data:
  disease_json: ../Src/Data/disease_list.json
  phenotype_json: ../Src/Data/phenotype.json
  positive_json: ../Src/Data/pos_datasets.json
  negative_json: ../Src/Data/neg_datasets.json
  text_json: ../Src/Data/text_data.json


model:
  out_path: Reuslt/model.pth
  checkpoint: Result/model.pth
  use_attention: false
  params:
    disease_embedding_dim: 64
    phenotype_embedding_dim: 32
    subcellular_embedding_dim: 32
    hidden_dim1: 256
    hidden_dim2: 128
    dropout_rate: 0.1


training:
  batch_size: 128
  epochs: 20
  patience: 10
  seed: 42
  lr: 0.001
  weight_decay: 0.01
  pos_weight: 3.0
  val_split: 0.2

prediction:
  output_file: Result/predictions.json
  batch_size: 1
  topk: 20
  seed: 42
  val_split: 0.1